pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building project'
                bat 'mvn clean compile'
            }
        }

        stage('Run Selenium') {
            steps {
                echo 'Running Selenium application'
                bat 'mvn exec:java "-Dexec.mainClass=CE.App"'
            }
        }
    }
}